// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Qb23pg2EMYWE04jpW--OGlpPmXjZ6a8',
    appId: '1:595525894937:web:3275f4d27c6acbaa98fb88',
    messagingSenderId: '595525894937',
    projectId: 'task-tide-22403',
    authDomain: 'task-tide-22403.firebaseapp.com',
    storageBucket: 'task-tide-22403.firebasestorage.app',
    measurementId: 'G-BKGR6S9JRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw7PHuZYB-azsZwJCmkk3Kctb0Kn9b2Qc',
    appId: '1:595525894937:android:46197e3da4d13bfa98fb88',
    messagingSenderId: '595525894937',
    projectId: 'task-tide-22403',
    storageBucket: 'task-tide-22403.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPpid6ORX1PWZwdjgR-eBhp6JpmLbEL3g',
    appId: '1:595525894937:ios:69acbfc0f0a69cc198fb88',
    messagingSenderId: '595525894937',
    projectId: 'task-tide-22403',
    storageBucket: 'task-tide-22403.firebasestorage.app',
    iosBundleId: 'com.example.taskTide1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPpid6ORX1PWZwdjgR-eBhp6JpmLbEL3g',
    appId: '1:595525894937:ios:69acbfc0f0a69cc198fb88',
    messagingSenderId: '595525894937',
    projectId: 'task-tide-22403',
    storageBucket: 'task-tide-22403.firebasestorage.app',
    iosBundleId: 'com.example.taskTide1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Qb23pg2EMYWE04jpW--OGlpPmXjZ6a8',
    appId: '1:595525894937:web:154fb49a0966d4c598fb88',
    messagingSenderId: '595525894937',
    projectId: 'task-tide-22403',
    authDomain: 'task-tide-22403.firebaseapp.com',
    storageBucket: 'task-tide-22403.firebasestorage.app',
    measurementId: 'G-04GDHJYGKH',
  );
}
